version: "3.7"
services:
  cv_server:
    build: ./server/nodejs
    environment:
      - SERVER_PORT=${SERVER_PORT}
    # expose:
    #   - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/nodejs/src:/srv/app/home-server/src
    command: npm run devstart
    networks:
      - traefik
      # - cv
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.services.cv_server.loadbalancer.server.port=${SERVER_PORT}
    #   - traefik.http.routers.cv_client.rule=Host(`api.jeffslord.com`)
    #   - traefik.docker.network=traefik
  cv_client:
    build: ./client/reactjs
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    volumes:
      - ./client/reactjs/src:/srv/app/home-client/src
      - ./client/reactjs/public:/srv/app/home-client/public
    command: npm run start
    networks:
      - traefik
      # - cv
    labels:
      - traefik.enable=true
      - traefik.http.routers.cv_client.rule=Host(`cv.jeffslord.com`)
      - traefik.http.services.cv_client.loadbalancer.server.port=${CLIENT_PORT}
      - traefik.docker.network=traefik

networks:
  traefik:
    external: true
  # cv:
  #   driver: bridge